(ns cljtiles.tutorials-0
  (:require [cljtiles.genblocks :as gb]))

(def vect
  (gb/chapter
   (gb/page (gb/coords [0 0])
            (gb/text "Hello, World!"))
   (gb/page (gb/coords [0 0]  [0 50])
            (gb/text "Hello, World!")
            (gb/text "I feel great."))
   (gb/page (gb/coords [0 0] [0 50])
            (gb/fun "println"
                    (gb/text "Hello, World!"))
            (gb/text "I feel great."))
   (gb/page (gb/coords [0 0] [0 50])
            (gb/text "Hello World!")
            (gb/fun "println" gb/slot))
   (gb/page (gb/coords [0 0] [0 50] [0 100])
            (gb/fun "str" gb/slot gb/slot)
            (gb/text "Clo")
            (gb/text "jure"))
   (gb/page (gb/coords [0 0] [100 0] [0 50] [0 100] [100 100])
            (gb/text "World")
            (gb/text " ")
            (gb/fun "str" gb/slot gb/slot gb/slot gb/slot)
            (gb/text "!")
            (gb/text "Hello,"))
   (gb/page (gb/coords [0 0] [50 0] [100 0] [150 0] [0 50])
            (gb/num 1)
            (gb/num 2)
            (gb/text " ")
            (gb/text " ")
            (gb/fun "str" (gb/num 3) gb/slot gb/slot (gb/text " ")
                    (gb/fun "str" gb/slot gb/slot (gb/text "Blast off!"))))))
